### ISSUE TITLE
pip install error "FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'"

### ISSUE THREAD

**Issue by ghost** [ianb/infinite-ai-array#2]
```
pip install git+https://github.com/ianb/infinite-ai-array.git
Collecting git+https://github.com/ianb/infinite-ai-array.git
  Cloning https://github.com/ianb/infinite-ai-array.git to /private/var/folders/dd/z5qxx2bx46l7_rqvvs45_ypc0000gn/T/pip-req-build-entgmcri
  Running command git clone --filter=blob:none --quiet https://github.com/ianb/infinite-ai-array.git /private/var/folders/dd/z5qxx2bx46l7_rqvvs45_ypc0000gn/T/pip-req-build-entgmcri
  Resolved https://github.com/ianb/infinite-ai-array.git to commit b56d82e61fe3d7ff0fd021d2212f7ff96424d855
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/dd/z5qxx2bx46l7_rqvvs45_ypc0000gn/T/pip-req-build-entgmcri/setup.py", line 7, in <module>
          with open("README.rst") as readme_file:
      FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by allanrbo** [comment]
Also got this while using repl.it.

**Comment by aidenfoxivey** [comment]
Same issue on my MacOS Ventura 13.1 machine with `pip 22.3.1 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)`.

**Comment by battaglia01** [comment]
Same here on M1 Monterey and pip 22.3. Tried installing via `pip3 install git+https://github.com/ianb/infinite-ai-array.git`.

**Comment by nyasour** [comment]
Same exact issue.

**Comment by ianb** [comment]
Oops, that was embarrassing
